version: "3"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  caddy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80

volumes:
  pgdata:
